events {}

http {
    resolver 1.1.1.1 8.8.8.8 valid=30s ipv6=off;

    limit_req_zone $binary_remote_addr zone=partner_api_limit:10m rate=10r/m;

    upstream backend_servers {
        zone backend_servers 256k;
        server backend1.example.com resolve;
        server backend2.example.com resolve;
        server backend3.example.com resolve;
    }

    server {
        listen 80;
        limit_req_status 429;

        location / {
            limit_req zone=partner_api_limit;
            proxy_pass http://backend_servers;
        }
    }
}
